PPWTP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', include('signup.urls')),
    path('donate/', include('donate.urls')),
    path('program/', include('program.urls')),
    path('news/', include('artikel.urls')),
    path('daftarDonasi/', include('daftarDonasi.urls')),
    path('about/', include('about.urls')),
    path('', include('crowd_funding.urls')),
    path('', include('artikel.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
    
]

about/urls.py
from django.urls import path
from about.views import base, about, testimony_list, create_testimony

urlpatterns = [
    path("400", base, name="base"),
    path("", about, name="about"),
    path("testimony_json", testimony_list, name="testimony_json"),
    path("create", create_testimony, name="create")
]

about/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Testimony(models.Model):
    
    this_name = models.CharField(max_length = 50)
    comment = models.CharField(max_length = 200)
    created_date = models.DateTimeField(auto_created=True)

    class Meta:
        verbose_name_plural = "Testimonies"

    def __str__(self):
        return "Message " + self.pk

about/forms.py
from django import forms

class TestimonyForm(forms.Form):
    attrs = {
        'class' : 'form-control'
    }

    message = forms.CharField(label="Testimony", max_length=50, required=False, widget=forms.TextInput(attrs=attrs))

about/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import Testimony
from .forms import TestimonyForm

# Create your views here.
team_member = ["Ailsa Zayyan Salsabila", 
               "Aurellia Dhya Andini", 
               "Thalia Talula Kesuma Putri", 
               "Yosua Krisnando Bagaskara"]

def base(request):
    response = {'web_title' : 'Base'}
    return render(request, 'base.html', response)

def about(request):
    response = {'web_title' : 'About', "members" : team_member, "testimony_form":TestimonyForm}
    return render(request, 'about.html', response)

def testimony_list(request):
    testimony = Testimony.objects.all().order_by("-created_date")
    response = {"data":list(testimony)}
    return JsonResponse(response)

def create_testimony(request):
    if request.method == "POST":
        this_name = request.POST["this_name"]
        comment = request.POST["comment"]
        tes = Testimony(this_name = this_name, comment = comment)
        tes.save()
        return HttpResponseRedirect('/about')

about/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block script %}
{% csrf_token %}
<script>
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    function add_testimony(name, message){
        $.ajax({
            type : "POST",
            url : "{% url 'create' %}",
            data :{
                this_name = name,
                comment = message,
                csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(){
                alert("Testimoni Berhasil Ditambahkan");
            }
        });
    }

    $("#submit_data").click(function(){
        var name = "{{user.first_name}}";
        var message = $("#id_message").val();
        add_testimony(name, message);
    });

    $(document).ready(function(){
        $.ajax({
            type:"GET",
            url: "{% url 'testimony_json' %}",
            datatype: "json",
            success:function(result){
                for(var i = 0; i < result.data.length; i++){
                    $("#testimony_div").append("<div class=\"media-body\">");
                    $("#testimony_div").append("<h5>" + result.data[i].this_name + "<small><i>Posted on" + result.data[i].created_date + "</i></small></h5>");
                    $("#testimony_div").append("<p>"+ result.data[i].comment + "</p>");
                }
                
            }
        });
    });
</script>
{% endblock script %}

{% block content %}

<div class="container mt-5 pt-5">
    <div class="row">
        <h1 class="text-center">OUR TEAM ARE:</h1>
    </div>
    <br>
    {% for i in members %}
    <div class="row d-flex justify-content-center">
        <h4 class="text-center p-2">{{ i }}</h4>
    </div>
    {% endfor %}
</div>

<div class="media border p-3" id="testimony_div">
    
</div>

</div class="container">
{% if user.is_authenticated %}
    <form>
        {{testimony_form}}
        <button id="submit_data" type="button" class="btn btn-info mt-4" disabled="disabled"></button>
    </form>
{% else %}
    <h5>SILAKAN LOGIN DI ATAS!<h5>
{% endif %}
{% endblock content %}

about/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="{% static 'img/ESM2.png' %}" />
    <title>{{web_title}} | SinarPerak</title>
    {% block style %}{% endblock style %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    {% block script %}
    
    {% endblock script %}
</head>
<body>
	<header>
        <div id="header" style="background-color:#8CD2EF">
            <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color:#8CD2EF">
                <img class="navbar-brand" src="{% static 'img/ESM2.png' %}" alt="hands connecting" style="width: 40px; height: 50px">
                <a class="navbar-brand" href="{% url 'home' %}"><h2>SinarPerak</h2></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}"><h3>Beranda</h3><span class="sr-only"></span></a>
                        </li>
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'get_user_total_donasi' %}"><h3>Profil</h3></a>
                                <a class="nav-link" href="{% url 'signup' %}"><h3>Halo, {{user.first_name}}!</h3></a>
                            {% else %}
                                <a class="nav-link" href="{% url 'signup' %}"><h3>Login</h3></a>
                            {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>